import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="flex min-h-screen flex-col bg-background">
          <main className="flex flex-1 flex-col max-w-4xl mx-auto w-full">
            {/* ヘッダー */}
            <header className="border-b bg-card px-4 py-4">
              <h1 className="text-2xl font-semibold">nc chat</h1>
            </header>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
